# This is a sample build configuration for .NET Core.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: microsoft/dotnet:3.0.100sdk

pipelines:
  default:
    - step:
        caches:
          - dotnetcore
        script: # Modify the commands below to build your repository.
          - export PROJECT_NAME=ROBaspCore
          - export TEST_NAME=ROBaspCore_UnitTests
          - dotnet restore
          - dotnet build $PROJECT_NAME
          - dotnet test $TEST_NAME
 #   - step:
 #       script:
 #       - pipe: atlassian/ftp-deploy:0.2.1
 #         variables:
 #           USER: $FTP_USERNAME
 #           PASSWORD: $FTP_PASSWORD
 #           SERVER: 'ftp://FTP.SITE4NOW.NET/'
 #           REMOTE_PATH: 'ROBTest'

